{% set name = "impyla" %}
{% set version = "0.18.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d5e301de056d9e53caa75ba0a6e5108b6078d87d10052824d2eb7a37bdcc52a4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - six 
    - bitarray 
    - thrift ==0.16.0
    - thrift_sasl >=0.4.2
    # TODO: see https://github.com/cloudera/impyla/issues/471
    - pure-sasl
    # - thrift-sasl ==0.4.3
    # - kerberos >=1.3.0

test:
  imports:
    - impala
    - impala.tests
    - impala.thrift
  requires:
    - pip
  commands:
    # Disabled for now since we override these dependencies
    # - pip check

about:
  home: https://github.com/cloudera/impyla
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Python client for the Impala distributed query engine

extra:
  recipe-maintainers:
    - mariusvniekerk
    - wesm
    - kszucs
    - cpcloud
