{% set name = "impyla" %}
{% set version = "0.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/impyla-{{ version }}.tar.gz
  sha256: 55d8c14454d9f18452ea9b4b0e81dca04d9fa0b9a9759b99bed9d6197d1f8292

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<3.12
    - six 
    - bitarray <3
    - thrift ==0.16.0
    - thrift_sasl ==0.4.3
    # TODO: see https://github.com/cloudera/impyla/issues/471
    - pure-sasl
    # - thrift-sasl ==0.4.3
    # - kerberos >=1.3.0
    # - python-kerberos >=1.3.0
    # - python-kerberos >=1.3.0
    # - python-kerberos >=1.3.0

test:
  imports:
    - impala
    - impala.tests
    - impala.thrift
  requires:
    - pip
    - python {{ python_min }}
  commands:
    # Disabled for now since we override these dependencies
    # - pip check

about:
  home: https://github.com/cloudera/impyla
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Python client for the Impala distributed query engine

extra:
  recipe-maintainers:
    - mariusvniekerk
    - wesm
    - kszucs
    - cpcloud
