{% set version = "0.17.0" %}

package:
  name: impyla
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/impyla/impyla-{{ version }}.tar.gz
  sha256: 2e44c8f594d75f40706394aa300c1f1f93ffa592b37b6e2bd02e0396a9443306

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - six
    - bitarray
    - thriftpy >=0.3.9
    - thriftpy2 >=0.4.0,<0.5.0  # [py3k]
    - thrift  # [py2k]
    - thrift_sasl >=0.2.1

test:
  imports:
    - impala
    - impala.tests
    - impala.thrift

about:
  home: https://github.com/cloudera/impyla
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Python client for the Impala distributed query engine

extra:
  recipe-maintainers:
    - mariusvniekerk
    - wesm
    - kszucs
