{% set version = "0.14.0" %}

package:
  name: impyla
  version: {{ version }}

source:
  fn: impyla-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/impyla/impyla-{{ version }}.tar.gz
  md5: 51301f014a386235e9d6532075e3fb2e

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - six
    - bitarray
    - thrift  # [py2k]
    - thriftpy >=0.3.5

  run:
    - python
    - setuptools
    - six
    - bitarray
    - thriftpy >=0.3.5
    - thrift  # [py2k]

test:
  imports:
    - impala
    - impala.tests
    - impala.thrift

about:
  home: https://github.com/cloudera/impyla
  license: Apache 2.0
  summary: 'Python client for the Impala distributed query engine'

extra:
  recipe-maintainers:
    - mariusvniekerk
    - wesm
