{% set name = "impyla" %}
{% set version = "0.17.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e44c8f594d75f40706394aa300c1f1f93ffa592b37b6e2bd02e0396a9443306

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - six
    - bitarray
    - thrift >=0.11.0
    - thrift_sasl >=0.4.2
    # TODO: see https://github.com/cloudera/impyla/issues/471
    - pure-sasl

test:
  imports:
    - impala
    - impala.tests
    - impala.thrift
  requires:
    - pip
  commands:
    # Disabled for now since we override these dependencies
    # - pip check

about:
  home: https://github.com/cloudera/impyla
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Python client for the Impala distributed query engine

extra:
  recipe-maintainers:
    - mariusvniekerk
    - wesm
    - kszucs
    - cpcloud
